# check for installed colordiff, rsync and vim
alias cp='cp -i'
alias cpv='rsync -ah --info=progress2'
alias df='df -H'
alias diff='colordiff'
alias du='du -ch'
alias edit='vim'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias k='kubectl'
alias kubectl="minikube kubectl --"
alias ll='ls -lh --color=auto'
alias ln='ln -i'
alias ls='ls --color=auto -F'
alias lt='ls --color=auto --human-readable --size -1 -S --classify'
alias mkdir='mkdir -pv'
alias mount='mount |column -t'
alias mv='mv -i'
alias now='date +"%T"'
alias nowdate='date +"%d-%m-%Y"'
alias nowtime='now'
alias path='echo -e ${PATH//:/\\n}'
alias svi='sudo vi'
alias va='source ./venv/bin/activate'
alias ve='python3 -m venv ./venv'
alias vi='vim'
alias vis='vim "+set si"'
