---

- name: "Backup dotfiles"
  hosts: localhost
  connection: local

  vars:
    dotfiles_to_backup:
      - .config/starship.toml
      - .gitconfig
      - .tmux.conf
      - .vim/colors/gruvbox8_hard.vim
      - .vim/colors/gruvbox8_soft.vim
      - .vim/colors/gruvbox8.vim
      - .vim/colors/seoul256.vim
      - .vim/colors/zenburn.vim
      - .vimrc
      - .zshrc
    dotfiles_repo_path: "~/dotfiles"

  tasks:

    - name: "Ensure dotfiles repository directiry exists"
      ansible.builtin.file:
        path: "{{ dotfiles_repo_path }}"
        state: directory
        mode: '750'

#    - name: "Backup specified dotfiles to repository"
#
#      ansible.builtin.copy:
#        src: "{{ ansible_env.HOME }}/{{ item }}"
#        dest: "{{ dotfiles_repo_path }}/{{ item }}"
#      loop: "{{ dotfiles_to_backup }}"
#      ignore_errors: true

    - name: "Get bash dotfiles into repository"
      ansible.builtin.include_role:
        name: df-bash

    - name: "Get vim dotfiles into repository"
      ansible.builtin.include_role:
        name: bkp-vim

    - name: "Push to git"
      ansible.builtin.include_role:
        name: push-dotfiles

...
