format = """
[  ](#ff6600)\
$shell\
$os\
$kubernetes\
[ ](fg:#4d95d5)\
$aws\
$username\
[](bg:#DA627D fg:#9A348E)\
$hostname\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
[](fg:#86BBD8 bg:#06969A)\
$docker_context\
[](fg:#06969A bg:#33658A)\
$terraform\
$time\
[ ](fg:#33658A)\
"""
command_timeout = 5000

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[ $user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'
disabled = false
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']

### GIT
[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'
disabled = false

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'
[line_break]
###

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[  $time ]($style)'

[kubernetes]
symbol = "⎈ "
format = " [$symbol$context( \\($namespace\\))]($style) "
style = "bg:white fg:bright-blue"
disabled = false

### AWS
[aws]
format = "on [$symbol $profile]($style) "
symbol="⛅"
disabled = false
###

[shell]
bash_indicator = 'bash'
zsh_indicator = 'zsh'
#fish_indicator = ' fsh 󰈺 '
fish_indicator = 'fsh'
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'bg:white fg:cyan bold'
disabled = false

[terraform]
format = '[ 󱁢 $version]($style) '
