---

vim_themes:
  - ".vim/colors/gruvbox8.vim"
  - ".vim/colors/gruvbox8_hard.vim"
  - ".vim/colors/gruvbox8_soft.vim"
  - ".vim/colors/seoul256.vim"
  - ".vim/colors/zenburn.vim"
vimrc: ".vimrc"

...
