---

# ensure vim directory and colors exist inn dotfiles
- name: "Ensure vim directory exists"
  ansible.builtin.file:
    path: "{{ dotfiles_repo_path }}/{{ item }}"
    state: directory
    mode: '750'
  loop:
    - ".vim"
    - ".vim/colors"

- name: "VIM Backup of rc and colors"
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/{{ item }}"
    dest: "{{ dotfiles_repo_path }}/vim/{{ item }}"
    mode: '660'
  loop:
    - "{{ vimrc }}"

- name: "VIM Backup and colors"
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/.vim/colors/{{ item }}"
    dest: "{{ dotfiles_repo_path }}/vim/colors/{{ item }}"
    mode: '660'
  loop:
    - "{{ vim_themes[0] }}"
    - "{{ vim_themes[1] }}"
    - "{{ vim_themes[2] }}"
    - "{{ vim_themes[3] }}"
    - "{{ vim_themes[4] }}"

...
