name: "Test local environment setup"
run-name: ${{ github.actor }} is learning GitHub Actions
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup brew and install all packages
        run: |
          echo "First GitHub Action"
          pwd
          ls -lha
          whoami
          sudo apt-get update
          sudo apt-get install -y build-essential procps curl file git wget findutils
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
          test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> ~/.bashrc
          cat ~/.bashrc
          xargs brew install < brew_installed.txt
          export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
        shell: bash

      - name: Set up fish shell
        run: |
          echo "Setting up fish shell now..."
          export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
          which fish
          fish -c 'echo "Fish shell version: $FISH_VERSION"'
          fish -c 'echo "Current shell: $SHELL"'
        shell: fish
