name: "Test local environment setup"
run-name: ${{ github.actor }}" is learning GitHub Actions

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "First GitHub Action"
