---

- name: "Check for changes in dotfiles repository"
  ansible.builtin.command:
    cmd: git -C "{{ dotfiles_repo_path }}" status --porcelain
  register: git_status
  changed_when: false

- name: "Commit changes and push dotfiles"
  when: git_status.stdout | length > 0
  block:
    - name: "Stage chhanges"
      ansible.builtin.command:
        cmd: git -C "{{ dotfiles_repo_path }}" add .

    - name: Commit changes
      ansible.builtin.command:
        cmd: git -C "{{ dotfiles_repo_path }}" commit -m "Backup dotfiles - {{ ansible_date_time.iso8601 }}"

    - name: Push changes
      ansible.builtin.command:
        cmd: git -C "{{ dotfiles_repo_path }}" push

...
